FROM python:3.12-slim
WORKDIR /app
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/ /app/backend/
COPY worker/ /app/worker/
CMD ["python", "worker/app/worker_daemon.py"]
