apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flowforge-ingress
  namespace: flowforge
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: flowforge.internal
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: flowforge-backend-service
                port:
                  number: 8000
