apiVersion: v1
kind: Secret
metadata:
  name: flowforge-secrets
  namespace: flowforge
type: Opaque
stringData:
  SECRET_KEY: "flowforge-k8s-production-super-secret-key-32chars"
  DATABASE_URL: "postgresql+asyncpg://flowforge:flowforge_secret@postgres-service:5432/flowforge"
  REDIS_URL: "redis://redis-service:6379/0"
  RABBITMQ_URL: "amqp://flowforge:flowforge_secret@rabbitmq-service:5672/"
